# Generated by Django 3.1.3 on 2020-11-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movemententry',
            name='list_type',
        ),
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='list_type',
        ),
        migrations.AddField(
            model_name='movemententry',
            name='entry_type',
            field=models.CharField(choices=[('ARR', 'Заезд'), ('LVN', 'Отъезд')], default='ARR', max_length=3, verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='entry_type',
            field=models.CharField(choices=[('ARR', 'Заезд'), ('LVN', 'Отъезд')], default='ARR', max_length=3, verbose_name='Тип записи'),
        ),
    ]
