# Generated by Django 3.1.3 on 2020-11-09 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201109_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='scheduled_datetime',
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='field_name',
            field=models.TextField(default=None, verbose_name='Имя измененного поля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='field_new_value',
            field=models.TextField(default=None, verbose_name='Новое значение поля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='field_old_value',
            field=models.TextField(default=None, verbose_name='Старое значение поля'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='field_type',
            field=models.TextField(default=None, verbose_name='Тип измененного поля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movemententry',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
    ]
