# Generated by Django 3.1.3 on 2020-11-09 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201109_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('ARR', 'Заезд'), ('LVN', 'Отъезд')], default='ARR', max_length=3, verbose_name='Тип списка')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='Дата и время заезда/отъезда')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.facilityobject', verbose_name='Производственный объект')),
            ],
        ),
        migrations.RemoveField(
            model_name='movemententry',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='movemententry',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='movemententry',
            name='scheduled_datetime',
        ),
        migrations.CreateModel(
            name='MovementListHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_datetime', models.DateTimeField(verbose_name='Время внесения изменений')),
                ('field_name', models.TextField(verbose_name='Имя измененного поля')),
                ('field_type', models.TextField(verbose_name='Тип измененного поля')),
                ('field_old_value', models.TextField(verbose_name='Старое значение поля')),
                ('field_new_value', models.TextField(verbose_name='Новое значение поля')),
                ('modified_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modified_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movementlist')),
            ],
            options={
                'verbose_name': 'Состояние списка',
                'verbose_name_plural': 'Состояния списков',
            },
        ),
        migrations.AddField(
            model_name='movemententry',
            name='movement_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.movementlist', verbose_name='Производственный объект'),
            preserve_default=False,
        ),
    ]
