# Generated by Django 3.1.3 on 2020-11-11 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201110_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='modified_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='movementlisthistory',
            name='modified_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
