# Generated by Django 3.1.3 on 2020-11-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201111_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='movementlisthistory',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
