# Generated by Django 3.1.3 on 2020-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201111_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='field_new_value',
        ),
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='field_old_value',
        ),
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='field_new_value',
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='field_old_value',
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='field_type',
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='serialized_model_delta',
            field=models.TextField(default=None, verbose_name='Сериализованные изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementlisthistory',
            name='serialized_model_delta',
            field=models.TextField(default=None, verbose_name='Сериализованные изменения'),
            preserve_default=False,
        ),
    ]
