# Generated by Django 3.1.3 on 2020-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201111_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemententryhistory',
            name='serialized_prev_delta',
            field=models.TextField(default=None, verbose_name='Данные до изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementlisthistory',
            name='serialized_prev_delta',
            field=models.TextField(default=None, verbose_name='Данные до изменения'),
            preserve_default=False,
        ),
    ]
