# Generated by Django 3.1.3 on 2020-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201112_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movemententryhistory',
            name='serialized_model_delta',
        ),
        migrations.RemoveField(
            model_name='movementlisthistory',
            name='serialized_model_delta',
        ),
        migrations.AddField(
            model_name='movemententryhistory',
            name='serialized_post_delta',
            field=models.TextField(default=None, verbose_name='Данные после изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementlisthistory',
            name='serialized_post_delta',
            field=models.TextField(default=None, verbose_name='Данные после изменения'),
            preserve_default=False,
        ),
    ]
