# Generated by Django 3.1.3 on 2020-11-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201112_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movemententry',
            options={'permissions': [('change_owned_movementlistentry', 'Право изменения записи созданной пользователем'), ('delete_owned_movementlistentry', 'Право удаления записи созданной пользователем')], 'verbose_name': 'Запись о заезде/отъезде', 'verbose_name_plural': 'Записи о заездах/отъездах'},
        ),
        migrations.AlterModelOptions(
            name='movementlist',
            options={'permissions': [('change_owned_movementlist', 'Право изменения списка созданного пользователем'), ('delete_owned_movementlist', 'Право удаления списка созданного пользователем')]},
        ),
    ]
