# Generated by Django 3.1.3 on 2020-11-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201118_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementlist',
            options={'permissions': [('change_owned_movementlist', 'Право изменения списка созданного пользователем'), ('delete_owned_movementlist', 'Право удаления списка созданного пользователем')], 'verbose_name': 'Список заездов/отъездов', 'verbose_name_plural': 'Списки заездов/отъездов'},
        ),
    ]
