# Generated by Django 3.1.3 on 2020-11-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201124_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemententry',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён?'),
        ),
        migrations.AddField(
            model_name='movementlist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён?'),
        ),
    ]
