# Generated by Django 3.1.3 on 2020-11-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201130_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='movemententry',
            name='was_modified',
            field=models.BooleanField(default=False, verbose_name='Был ли список изменен?'),
        ),
        migrations.AddField(
            model_name='movementlist',
            name='was_modified',
            field=models.BooleanField(default=False, verbose_name='Был ли список изменен?'),
        ),
        migrations.AlterField(
            model_name='movementlist',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения модели'),
        ),
    ]
