# Generated by Django 3.1.3 on 2020-12-12 16:47

from django.db import migrations


def create_default_facility(app, schema_editor):
    FacilityObject = app.get_model('main', 'FacilityObject')
    FacilityObject.objects.create(
        name="Рудник Шануч",
        slug="shanuch-mine",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201130_1441'),
    ]

    operations = [
        migrations.RunPython(create_default_facility)
    ]
