# Generated by Django 3.1.3 on 2020-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201212_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movementlist',
            options={'permissions': [('change_owned_movementlist', 'Право изменения списка созданного пользователем'), ('delete_owned_movementlist', 'Право удаления списка созданного пользователем')], 'verbose_name': 'Список заездов/выездов', 'verbose_name_plural': 'Списки заездов/выездов'},
        ),
        migrations.AddField(
            model_name='movementlist',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место выезда/заезда'),
        ),
        migrations.AddField(
            model_name='movementlist',
            name='watch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вахта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
    ]
