# Generated by Django 3.1.3 on 2020-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201220_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_senior',
            field=models.BooleanField(default=False, verbose_name='Старший'),
        ),
    ]
