# Generated by Django 3.1.3 on 2020-12-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_employee_is_senior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movemententry',
            options={'permissions': [('change_owned_movemententry', 'Право изменения записи созданной пользователем'), ('delete_owned_movemententry', 'Право удаления записи созданной пользователем')], 'verbose_name': 'Запись о заезде/выезде', 'verbose_name_plural': 'Записи о заездах/выездах'},
        ),
        migrations.AlterModelOptions(
            name='movementlist',
            options={'permissions': [('change_owned_movementlist', 'Право изменения списка созданного пользователем'), ('delete_owned_movementlist', 'Право удаления списка созданного пользователем'), ('set_watch_field', 'Право установки значения вахты')], 'verbose_name': 'Список заездов/выездов', 'verbose_name_plural': 'Списки заездов/выездов'},
        ),
        migrations.AlterField(
            model_name='movementlist',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место заезда/выезда'),
        ),
        migrations.AlterField(
            model_name='movementlist',
            name='scheduled_datetime',
            field=models.DateTimeField(verbose_name='Дата и время заезда/выезда'),
        ),
    ]
